# Generated by Django 5.0.6 on 2026-06-14 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id_campus', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID корпуса')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Полный адрес')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
        migrations.CreateModel(
            name='CityDistrict',
            fields=[
                ('id_district', models.AutoField(primary_key=True, serialize=False, verbose_name='ID округа')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Городской округ',
                'verbose_name_plural': 'Городские округа',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код страны')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='DisciplineReference',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Код дисциплины')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('type', models.CharField(choices=[('общеобразовательный', 'Общеобразовательный'), ('общепрофессиональный', 'Общепрофессиональный'), ('профессиональный_модуль', 'Профессиональный модуль'), ('мдк', 'МДК'), ('практика', 'Практика'), ('гиа', 'ГИА')], max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Справочник дисциплин',
                'verbose_name_plural': 'Справочник дисциплин',
            },
        ),
        migrations.CreateModel(
            name='DocumentGenerationType',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('template_path', models.CharField(max_length=255, verbose_name='Путь к шаблон DOCX')),
            ],
            options={
                'verbose_name': 'Тип документа для генерации',
                'verbose_name_plural': 'Типы документов для генерации',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
        migrations.CreateModel(
            name='EducationInstitution',
            fields=[
                ('id_institution', models.AutoField(primary_key=True, serialize=False, verbose_name='ID учреждения')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('общеобразовательная_средняя', 'Общеобразовательная средняя'), ('лицей', 'Лицей'), ('гимназия', 'Гимназия'), ('техникум', 'Техникум'), ('колледж', 'Колледж'), ('ПТУ', 'ПТУ'), ('другое', 'Другое')], max_length=100, verbose_name='Тип')),
                ('profile', models.CharField(blank=True, max_length=100, null=True, verbose_name='Профиль класса')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Учебное заведение',
                'verbose_name_plural': 'Учебные заведения',
            },
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False, verbose_name='ID формы')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Форма занятости',
                'verbose_name_plural': 'Формы занятости',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id_family', models.AutoField(primary_key=True, serialize=False, verbose_name='ID семьи')),
                ('minors_count', models.IntegerField(blank=True, null=True, verbose_name='Кол-во несовершеннолетних')),
                ('adults_count', models.IntegerField(blank=True, null=True, verbose_name='Кол-во совершеннолетних')),
                ('status', models.CharField(choices=[('полная', 'Полная'), ('родители_в_разводе', 'Родители в разводе'), ('малообеспеченная', 'Малообеспеченная'), ('многодетная', 'Многодетная'), ('потеря_кормильца', 'Потеря кормильца'), ('мать_одиночка', 'Мать-одиночка'), ('отец_одиночка', 'Отец-одиночка'), ('ребенок_инвалид', 'Ребенок-инвалид'), ('ребенок_сирота', 'Ребенок-сирота'), ('под_опекой', 'Под опекой'), ('приёмная_семья', 'Приёмная семья'), ('повторный_брак', 'Повторный брак')], max_length=100, verbose_name='Статус семьи')),
                ('housing_type', models.CharField(choices=[('в_собственном_жилье_с_родителями', 'В собственном жилье с родителями'), ('в_съёмном_жилье_с_родителями', 'В съёмном жилье с родителями'), ('отдельно_от_родителей', 'Отдельно от родителей'), ('другое', 'Другое')], max_length=100, verbose_name='Тип жилья')),
            ],
            options={
                'verbose_name': 'Семья',
                'verbose_name_plural': 'Семьи',
            },
        ),
        migrations.CreateModel(
            name='FinancialAidGround',
            fields=[
                ('id_ground', models.AutoField(primary_key=True, serialize=False, verbose_name='ID основания')),
                ('name', models.TextField(verbose_name='Название')),
                ('requires_mo', models.BooleanField(default=False, verbose_name='Требует проживания в МО')),
                ('required_docs', models.JSONField(help_text='JSON-массив кодов из Типы_документов', verbose_name='Необходимые документы (коды)')),
            ],
            options={
                'verbose_name': 'Основание мат. помощи',
                'verbose_name_plural': 'Основания мат. помощи',
            },
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id_health', models.AutoField(primary_key=True, serialize=False, verbose_name='ID здоровья')),
                ('status', models.CharField(choices=[('здоров', 'Здоров'), ('часто_болею', 'Часто болею'), ('хронические_заболевания', 'Хронические заболевания'), ('инвалидность', 'Инвалидность')], max_length=100, verbose_name='Состояние')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Диагноз (шифруется)')),
                ('diagnosis_scan', models.FileField(blank=True, null=True, upload_to='docs/health/', verbose_name='Скан диагноза')),
                ('oms_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер полиса ОМС')),
                ('oms_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи ОМС')),
                ('oms_issuer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан ОМС')),
                ('oms_scan', models.FileField(blank=True, null=True, upload_to='docs/health/', verbose_name='Скан полиса')),
                ('oms_absence_reason', models.TextField(blank=True, null=True, verbose_name='Причина отсутствия полиса')),
            ],
            options={
                'verbose_name': 'Здоровье',
                'verbose_name_plural': 'Здоровье',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id_industry', models.AutoField(primary_key=True, serialize=False, verbose_name='ID отрасли')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
            },
        ),
        migrations.CreateModel(
            name='Military',
            fields=[
                ('id_military', models.AutoField(primary_key=True, serialize=False, verbose_name='ID ВУ')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер приписного')),
                ('commissariat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Военкомат')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('fitness_category', models.CharField(blank=True, choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д')], max_length=10, null=True, verbose_name='Категория годности')),
                ('absence_reason', models.TextField(blank=True, null=True, verbose_name='Причина отсутствия')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='docs/military/', verbose_name='Скан ВУ')),
            ],
            options={
                'verbose_name': 'Воинский учет',
                'verbose_name_plural': 'Воинский учет',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID приказа (НОМЕР-ГОД)')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('date', models.DateField(help_text='Формат: ДД.ММ.ГГГГ', verbose_name='Дата')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='orders/', verbose_name='Файл приказа')),
                ('type', models.CharField(choices=[('зачисление', 'Зачисление'), ('отчисление', 'Отчисление'), ('перевод', 'Перевод'), ('иное', 'Иное')], max_length=50, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('inn', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='ИНН')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Юридическое название')),
                ('short_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сокращенное название')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН')),
                ('rusprofile_link', models.URLField(blank=True, null=True, verbose_name='Ссылка Rusprofile')),
                ('index', models.CharField(blank=True, max_length=10, null=True, verbose_name='Индекс')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Субъект РФ')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Населенный пункт')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица')),
                ('building', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом')),
                ('extra_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Доп. информация')),
                ('fact_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фактический адрес')),
                ('director_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО директора')),
                ('director_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность директора')),
                ('director_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон директора')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email организации')),
                ('responsible_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО ответственного')),
                ('responsible_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность ответственного')),
                ('responsible_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон ответственного')),
                ('mentor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО наставника ОО')),
                ('mentor_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность наставника ОО')),
                ('mentor_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон наставника ОО')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка')),
                ('account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Расчетный счет')),
                ('corr_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Корр. счет')),
                ('bik', models.CharField(blank=True, max_length=20, null=True, verbose_name='БИК')),
                ('basis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Основание действий')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id_passport', models.AutoField(primary_key=True, serialize=False, verbose_name='ID паспорта')),
                ('is_foreigner', models.BooleanField(default=False, verbose_name='Иностранный гражданин')),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True, verbose_name='Гражданство')),
                ('series_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Серия и номер')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('issuer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан')),
                ('unit_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код подразделения')),
                ('region_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион и город')),
                ('address_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес детально')),
                ('fact_region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фактический регион')),
                ('fact_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фактический адрес детально')),
                ('temp_reg', models.BooleanField(default=False, verbose_name='Временная прописка')),
                ('absence_reason', models.TextField(blank=True, null=True, verbose_name='Причина отсутствия')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='docs/passports/', verbose_name='Скан паспорта')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_profile', models.AutoField(primary_key=True, serialize=False, verbose_name='ID профиля')),
                ('it_skills', models.JSONField(blank=True, null=True, verbose_name='IT-навыки')),
                ('programming_langs', models.TextField(blank=True, null=True, verbose_name='Языки программирования')),
                ('creative_skills', models.JSONField(blank=True, null=True, verbose_name='Творческие навыки')),
                ('school_participation', models.JSONField(blank=True, null=True, verbose_name='Участие в школе')),
                ('college_participation', models.JSONField(blank=True, null=True, verbose_name='Участие в техникуме')),
                ('achievements', models.JSONField(blank=True, null=True, verbose_name='Достижения')),
                ('hobbies', models.TextField(blank=True, null=True, verbose_name='Хобби')),
                ('extra_edu', models.TextField(blank=True, null=True, verbose_name='Дополнительное образование')),
                ('social_networks', models.JSONField(blank=True, null=True, verbose_name='Соцсети')),
                ('motivation_college', models.JSONField(blank=True, null=True, verbose_name='Мотивация техникум')),
                ('motivation_specialty', models.JSONField(blank=True, null=True, verbose_name='Мотивация специальность')),
                ('desired_participation', models.JSONField(blank=True, null=True, verbose_name='Желаемое участие')),
                ('foreign_langs', models.JSONField(blank=True, null=True, verbose_name='Иностранные языки')),
                ('drivers_license', models.JSONField(blank=True, null=True, verbose_name='Водительские права')),
                ('sports_ranks', models.TextField(blank=True, null=True, verbose_name='Спортивные разряды')),
                ('character_behavior', models.TextField(blank=True, null=True, verbose_name='Характер и поведение')),
            ],
            options={
                'verbose_name': 'Профиль студента',
                'verbose_name_plural': 'Профили студентов',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id_qualification', models.AutoField(primary_key=True, serialize=False, verbose_name='ID квалификации')),
                ('name', models.CharField(max_length=255, verbose_name='Квалификация')),
                ('professionalitet_role', models.CharField(blank=True, choices=[('ядро', 'Ядро'), ('сеть', 'Сеть'), ('нет', 'Нет')], max_length=50, null=True, verbose_name='Роль в профессионалитете')),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False, verbose_name='ID области')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.CharField(help_text='Только латиница и _', max_length=50, primary_key=True, serialize=False, verbose_name='ID роли')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id_setting', models.AutoField(primary_key=True, serialize=False, verbose_name='ID настройки')),
                ('field_name', models.CharField(max_length=100, unique=True, verbose_name='Название поля')),
                ('value', models.TextField(verbose_name='Значение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Настройка техникума',
                'verbose_name_plural': 'Настройки техникума',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id_specialty', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Код ФГОС')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('level', models.CharField(blank=True, choices=[('специальность', 'Специальность'), ('профессия', 'Профессия')], max_length=50, null=True, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(primary_key=True, serialize=False, verbose_name='ID пользователя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('requires_password_change', models.BooleanField(default=True, verbose_name='Требует смены пароля')),
                ('esia_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ESIA ID (Госуслуги)')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Статус персонала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id_member', models.AutoField(primary_key=True, serialize=False, verbose_name='ID члена семьи')),
                ('relation', models.CharField(choices=[('мать', 'Мать'), ('отец', 'Отец'), ('брат', 'Брат'), ('сестра', 'Сестра'), ('опекун', 'Опекун'), ('мачеха', 'Мачеха'), ('отчим', 'Отчим'), ('бабушка', 'Бабушка'), ('дедушка', 'Дедушка'), ('другое', 'Другое')], max_length=100, verbose_name='Степень родства')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='Образование')),
                ('workplace', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('is_pensioner', models.BooleanField(default=False, verbose_name='Пенсионер')),
                ('is_svo', models.BooleanField(default=False, verbose_name='На СВО')),
                ('is_priority_contact', models.BooleanField(default=False, verbose_name='Приоритетный контакт')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.family', verbose_name='Семья')),
            ],
            options={
                'verbose_name': 'Член семьи',
                'verbose_name_plural': 'Члены семьи',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='fin_aid_ground',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.financialaidground', verbose_name='Основание мат. помощи'),
        ),
        migrations.CreateModel(
            name='GEKProtocol',
            fields=[
                ('id_protocol', models.AutoField(primary_key=True, serialize=False, verbose_name='ID протокола')),
                ('number', models.CharField(max_length=50, verbose_name='Номер протокола')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('gia_type', models.CharField(choices=[('только_дэ', 'Только ДЭ'), ('только_диплом', 'Только диплом'), ('дэ_и_диплом', 'ДЭ и диплом')], max_length=50, verbose_name='Тип ГИА')),
                ('chairman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Председатель')),
            ],
            options={
                'verbose_name': 'Протокол ГЭК',
                'verbose_name_plural': 'Протоколы ГЭК',
            },
        ),
        migrations.CreateModel(
            name='GIAResult',
            fields=[
                ('id_result', models.AutoField(primary_key=True, serialize=False, verbose_name='ID результата')),
                ('de_score', models.IntegerField(blank=True, null=True, verbose_name='Балл ДЭ')),
                ('de_grade', models.CharField(blank=True, choices=[('отлично', 'Отлично'), ('хорошо', 'Хорошо'), ('удовл.', 'Удовлетворительно'), ('неуд.', 'Неудовлетворительно')], max_length=50, null=True, verbose_name='Оценка ДЭ')),
                ('diploma_topic', models.TextField(blank=True, null=True, verbose_name='Тема диплома')),
                ('diploma_grade', models.CharField(blank=True, choices=[('отлично', 'Отлично'), ('хорошо', 'Хорошо'), ('удовл.', 'Удовлетворительно'), ('неуд.', 'Неудовлетворительно')], max_length=50, null=True, verbose_name='Оценка диплома')),
                ('final_gia_grade', models.CharField(choices=[('отлично', 'Отлично'), ('хорошо', 'Хорошо'), ('удовл.', 'Удовлетворительно'), ('неуд.', 'Неудовлетворительно')], max_length=50, verbose_name='Итоговая оценка ГИА')),
                ('diploma_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_diplomas', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель диплома')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gekprotocol', verbose_name='Протокол')),
            ],
            options={
                'verbose_name': 'Результат ГИА',
                'verbose_name_plural': 'Результаты ГИА',
            },
        ),
        migrations.CreateModel(
            name='GIADefenseQuestion',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False, verbose_name='ID вопроса')),
                ('question_number', models.IntegerField(verbose_name='Номер вопроса')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('student_answer', models.TextField(blank=True, null=True, verbose_name='Ответ студента')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
                ('gia_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.giaresult', verbose_name='Результат ГИА')),
            ],
            options={
                'verbose_name': 'Вопрос на защите',
                'verbose_name_plural': 'Вопросы на защите',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_group', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID группы')),
                ('year_start', models.IntegerField(verbose_name='Год поступления')),
                ('year_end', models.IntegerField(verbose_name='Год окончания')),
                ('duration', models.CharField(choices=[('1 год 10 месяцев', '1 год 10 месяцев'), ('2 года', '2 года'), ('2 года 6 месяцев', '2 года 6 месяцев'), ('2 года 10 месяцев', '2 года 10 месяцев'), ('3 года 10 месяцев', '3 года 10 месяцев'), ('4 года 10 месяцев', '4 года 10 месяцев')], max_length=50, verbose_name='Срок обучения')),
                ('form', models.CharField(choices=[('очная', 'Очная'), ('очно-заочная', 'Очно-заочная'), ('заочная', 'Заочная')], max_length=50, verbose_name='Форма обучения')),
                ('financing', models.CharField(choices=[('бюджет', 'Бюджет'), ('внебюджет', 'Внебюджет')], max_length=50, verbose_name='Финансирование')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.campus', verbose_name='Корпус')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Куратор')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.qualification', verbose_name='Квалификация')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AddField(
            model_name='gekprotocol',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.group', verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='DisciplineInGroup',
            fields=[
                ('id_record', models.AutoField(primary_key=True, serialize=False, verbose_name='ID записи')),
                ('semester', models.IntegerField(verbose_name='Семестр')),
                ('assessment_form', models.CharField(choices=[('экзамен', 'Экзамен'), ('дифференцированный_зачет', 'Дифференцированный зачет'), ('зачет', 'Зачет'), ('курсовая_работа', 'Курсовая работа')], max_length=50, verbose_name='Форма аттестации')),
                ('hours', models.IntegerField(blank=True, null=True, verbose_name='Объем часов')),
                ('discipline_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.disciplinereference', verbose_name='Дисциплина')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Дисциплина в группе',
                'verbose_name_plural': 'Дисциплины в группе',
            },
        ),
        migrations.CreateModel(
            name='AttendanceTable',
            fields=[
                ('id_table', models.AutoField(primary_key=True, serialize=False, verbose_name='ID табеля')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Куратор')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Табель посещаемости',
                'verbose_name_plural': 'Табели посещаемости',
                'unique_together': {('group', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentSchedule',
            fields=[
                ('id_schedule', models.AutoField(primary_key=True, serialize=False, verbose_name='ID расписания')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время проведения')),
                ('room', models.CharField(blank=True, max_length=50, null=True, verbose_name='Аудитория')),
                ('retake_date', models.DateField(blank=True, null=True, verbose_name='Дата пересдачи')),
                ('retake_time', models.TimeField(blank=True, null=True, verbose_name='Время пересдачи')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
                ('discipline_in_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplineingroup', verbose_name='Дисциплина')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Расписание аттестации',
                'verbose_name_plural': 'Расписание аттестации',
            },
        ),
        migrations.CreateModel(
            name='MCK',
            fields=[
                ('id_mck', models.AutoField(primary_key=True, serialize=False, verbose_name='ID МЦК')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сокращенное наименование')),
                ('chairman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Председатель')),
            ],
            options={
                'verbose_name': 'Методическая цикловая комиссия',
                'verbose_name_plural': 'Методические цикловые комиссии',
            },
        ),
        migrations.AddField(
            model_name='disciplineingroup',
            name='mck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mck', verbose_name='МЦК'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id_module', models.CharField(help_text='Формат: КОД_МОДУЛЯ_ГРУППА', max_length=100, primary_key=True, serialize=False, verbose_name='ID модуля')),
                ('code', models.CharField(max_length=50, verbose_name='Код модуля')),
                ('name', models.TextField(verbose_name='Название модуля')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
            },
        ),
        migrations.CreateModel(
            name='PracticeOrder',
            fields=[
                ('id_order', models.CharField(help_text='Формат: №НОМЕР от ДД.ММ.ГГГГ', max_length=100, primary_key=True, serialize=False, verbose_name='ID приказа практики')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='Дата сдачи отчета')),
                ('type', models.CharField(choices=[('учебная', 'Учебная'), ('производственная', 'Производственная'), ('преддипломная', 'Преддипломная')], max_length=50, verbose_name='Вид практики')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='docs/practice_orders/', verbose_name='Файл приказа')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Приказ о практике',
                'verbose_name_plural': 'Приказы о практике',
            },
        ),
        migrations.AddField(
            model_name='qualification',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.specialty', verbose_name='Специальность'),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id_statement', models.AutoField(primary_key=True, serialize=False, verbose_name='ID ведомости')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер ведомости')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('status', models.CharField(choices=[('в_работе', 'В работе'), ('закрыта', 'Закрыта'), ('сдана_в_архив', 'Сдана в архив')], default='в_работе', max_length=50, verbose_name='Статус')),
                ('discipline_in_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.disciplineingroup', verbose_name='Дисциплина')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Ведомость',
                'verbose_name_plural': 'Ведомости',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('snils', models.CharField(help_text='Формат: XXX-XXX-XXX XX', max_length=20, primary_key=True, serialize=False, verbose_name='СНИЛС')),
                ('snils_file', models.FileField(blank=True, null=True, upload_to='docs/students/', verbose_name='Скан СНИЛС')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('мужской', 'Мужской'), ('женский', 'Женский')], max_length=10, verbose_name='Пол')),
                ('birth_place', models.CharField(max_length=255, verbose_name='Место рождения')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('inn_file', models.FileField(blank=True, null=True, upload_to='docs/students/', verbose_name='Скан ИНН')),
                ('pd_consent', models.BooleanField(default=False, verbose_name='Согласие на ПДн')),
                ('pd_consent_date', models.DateField(blank=True, null=True, verbose_name='Дата согласия')),
                ('status', models.CharField(choices=[('обучается (студент)', 'Обучается (студент)'), ('не завершил обучение: академический отпуск', 'Академический отпуск'), ('не завершил обучение: отчислен по собственному желанию', 'Отчислен по собственному желанию'), ('не завершил обучение: отчислен в связи с неуспеваемостью', 'Отчислен в связи с неуспеваемостью'), ('завершил обучение (выпускник)', 'Завершил обучение (выпускник)')], max_length=100, verbose_name='Статус обучения')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('photo_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к фото СКУД')),
                ('study_plan', models.CharField(choices=[('стандартный', 'Стандартный'), ('иуп', 'ИУП')], default='стандартный', max_length=50, verbose_name='Учебный план')),
                ('dual_edu', models.BooleanField(default=False, verbose_name='Дуальное обучение')),
                ('education', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.educationinstitution', verbose_name='Учебное заведение')),
                ('family', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.family', verbose_name='Семья')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.group', verbose_name='Группа')),
                ('health', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.health', verbose_name='Здоровье')),
                ('military', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.military', verbose_name='Воинский учет')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.order', verbose_name='Приказ о зачислении')),
                ('passport', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.passport', verbose_name='Паспорт')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile', verbose_name='Профиль')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='StatementGrade',
            fields=[
                ('id_grade', models.AutoField(primary_key=True, serialize=False, verbose_name='ID оценки')),
                ('grade', models.CharField(blank=True, choices=[('5 (отлично)', '5 (отлично)'), ('4 (хорошо)', '4 (хорошо)'), ('3 (удовлетворительно)', '3 (удовлетворительно)'), ('2 (неудовлетворительно)', '2 (неудовлетворительно)'), ('н/а (не допущен)', 'н/а (не допущен)'), ('зачтено', 'Зачтено'), ('не_зачтено', 'Не зачтено')], max_length=50, null=True, verbose_name='Оценка')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('is_retake', models.BooleanField(default=False, verbose_name='Является пересдачей')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.statement', verbose_name='Ведомость')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Оценка в ведомости',
                'verbose_name_plural': 'Оценки в ведомости',
            },
        ),
        migrations.AddField(
            model_name='giaresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Студент'),
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id_employment', models.AutoField(primary_key=True, serialize=False, verbose_name='ID трудоустройства')),
                ('is_cluster_partner', models.BooleanField(default=False, verbose_name='Труд. у партнера кластера')),
                ('is_by_profession', models.BooleanField(default=False, verbose_name='Трудоустройство по профессии')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('scan_szv_td', models.FileField(blank=True, null=True, upload_to='docs/employment/', verbose_name='Скан СЗВ-ТД')),
                ('scan_self_employed', models.FileField(blank=True, null=True, upload_to='docs/employment/', verbose_name='Скан самозанятости')),
                ('scan_ip', models.FileField(blank=True, null=True, upload_to='docs/employment/', verbose_name='Скан ИП')),
                ('scan_self_employed_tax', models.FileField(blank=True, null=True, upload_to='docs/employment/', verbose_name='Скан налогов самозанятого')),
                ('city_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.citydistrict', verbose_name='Городской округ')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.employmenttype', verbose_name='Форма занятости')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.industry', verbose_name='Отрасль')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization', verbose_name='Организация')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Трудоустройство',
                'verbose_name_plural': 'Трудоустройства',
            },
        ),
        migrations.CreateModel(
            name='AttendanceTableRow',
            fields=[
                ('id_row', models.AutoField(primary_key=True, serialize=False, verbose_name='ID строки')),
                ('study_days', models.IntegerField(default=0, verbose_name='Учебные дни')),
                ('sick_leave', models.IntegerField(default=0, verbose_name='Больничный')),
                ('practice', models.IntegerField(default=0, verbose_name='Практика')),
                ('truancy', models.IntegerField(default=0, verbose_name='Прогулы')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attendancetable', verbose_name='Табель')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Строка табеля',
                'verbose_name_plural': 'Строки табеля',
            },
        ),
        migrations.CreateModel(
            name='StudentPracticePlace',
            fields=[
                ('id_place', models.AutoField(primary_key=True, serialize=False, verbose_name='ID места практики')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность студента')),
                ('status', models.CharField(choices=[('назначен', 'Назначен'), ('проходит', 'Проходит'), ('завершил', 'Завершил'), ('не_назначен', 'Не назначен'), ('отчислен', 'Отчислен')], default='назначен', max_length=50, verbose_name='Статус')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.practiceorder', verbose_name='Приказ практики')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='Организация')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Студент')),
                ('teacher1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_teacher1', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель 1')),
                ('teacher2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_teacher2', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель 2')),
            ],
            options={
                'verbose_name': 'Место практики студента',
                'verbose_name_plural': 'Места практик студентов',
            },
        ),
        migrations.CreateModel(
            name='PracticeTask',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False, verbose_name='ID задания')),
                ('topic_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер темы')),
                ('topic_name', models.TextField(verbose_name='Название темы')),
                ('work_types', models.TextField(verbose_name='Виды работ')),
                ('competencies', models.TextField(verbose_name='Формируемые компетенции')),
                ('hours', models.IntegerField(verbose_name='Количество часов')),
                ('practice_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentpracticeplace', verbose_name='Место практики')),
            ],
            options={
                'verbose_name': 'Задание практики',
                'verbose_name_plural': 'Задания практики',
            },
        ),
        migrations.CreateModel(
            name='PracticeDiary',
            fields=[
                ('id_entry', models.AutoField(primary_key=True, serialize=False, verbose_name='ID записи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('work_content', models.TextField(verbose_name='Содержание работы')),
                ('hours', models.IntegerField(verbose_name='Количество часов')),
                ('is_approved_by_org', models.BooleanField(default=False, verbose_name='Отметка руководителя орг.')),
                ('practice_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentpracticeplace', verbose_name='Место практики')),
            ],
            options={
                'verbose_name': 'Запись дневника практики',
                'verbose_name_plural': 'Дневник практики',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PracticeControlPoint',
            fields=[
                ('id_point', models.AutoField(primary_key=True, serialize=False, verbose_name='ID точки')),
                ('control_date', models.DateField(verbose_name='Дата контроля')),
                ('work_done', models.TextField(verbose_name='Выполненная работа')),
                ('is_signed_by_org', models.BooleanField(default=False, verbose_name='Подпись руководителя орг.')),
                ('practice_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentpracticeplace', verbose_name='Место практики')),
            ],
            options={
                'verbose_name': 'Контрольная точка',
                'verbose_name_plural': 'Контрольные точки',
            },
        ),
        migrations.CreateModel(
            name='PracticeAttestation',
            fields=[
                ('id_attestation', models.AutoField(primary_key=True, serialize=False, verbose_name='ID аттестации')),
                ('competencies_eval', models.JSONField(blank=True, null=True, verbose_name='Оценка компетенций')),
                ('characteristic_text', models.TextField(blank=True, null=True, verbose_name='Текст характеристики')),
                ('recommended_grade', models.CharField(blank=True, choices=[('отлично', 'Отлично'), ('хорошо', 'Хорошо'), ('удовлетворительно', 'Удовлетворительно'), ('неудовлетворительно', 'Неудовлетворительно')], max_length=50, null=True, verbose_name='Рекомендуемая оценка')),
                ('fill_date', models.DateField(verbose_name='Дата заполнения')),
                ('practice_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.studentpracticeplace', verbose_name='Место практики')),
            ],
            options={
                'verbose_name': 'Аттестация практики',
                'verbose_name_plural': 'Аттестации практики',
            },
        ),
        migrations.CreateModel(
            name='TargetContract',
            fields=[
                ('id_contract', models.CharField(help_text='Формат: №НОМЕР от ДД.ММ.ГГГГ', max_length=100, primary_key=True, serialize=False, verbose_name='ID договора')),
                ('has_contract', models.BooleanField(default=False, verbose_name='Наличие договора')),
                ('format', models.CharField(blank=True, choices=[('оформлен_на_рвр', 'Оформлен на РвР'), ('в_бумажном_виде', 'В бумажном виде')], max_length=50, null=True, verbose_name='Формат')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Предприятие')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Целевой договор',
                'verbose_name_plural': 'Целевые договоры',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='target_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.targetcontract', verbose_name='Целевой договор'),
        ),
        migrations.CreateModel(
            name='GEKMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('зам_председателя', 'Зам. председателя'), ('член_комиссии', 'Член комиссии'), ('секретарь', 'Секретарь')], max_length=50, verbose_name='Роль в комиссии')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gekprotocol', verbose_name='Протокол')),
            ],
            options={
                'verbose_name': 'Член ГЭК',
                'verbose_name_plural': 'Члены ГЭК',
                'unique_together': {('protocol', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PracticeOrderModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.module', verbose_name='Модуль')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.practiceorder', verbose_name='Приказ практики')),
            ],
            options={
                'verbose_name': 'Модуль в приказе',
                'verbose_name_plural': 'Модули в приказах',
                'unique_together': {('order', 'module')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='qualification',
            unique_together={('specialty', 'name')},
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Роль пользователя',
                'verbose_name_plural': 'Роли пользователей',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
