# Generated by Django 5.0.6 on 2026-06-21 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentschedule',
            options={'ordering': ['date', 'time', 'group'], 'verbose_name': 'Запись расписания аттестации', 'verbose_name_plural': 'Расписание аттестации'},
        ),
        migrations.RemoveField(
            model_name='assessmentschedule',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='assessmentschedule',
            name='discipline_in_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='core.disciplineingroup', verbose_name='Дисциплина в группе'),
        ),
        migrations.AlterField(
            model_name='assessmentschedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='assessmentschedule',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='assessmentschedule',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.CreateModel(
            name='AssessmentTeacher',
            fields=[
                ('id_assessment_teacher', models.AutoField(primary_key=True, serialize=False, verbose_name='ID записи')),
                ('role', models.CharField(choices=[('primary', 'Основной преподаватель'), ('co', 'Со-преподаватель')], default='primary', max_length=20, verbose_name='Роль')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_teachers', to='core.assessmentschedule', verbose_name='Запись расписания')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_teaching', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Преподаватель в расписании',
                'verbose_name_plural': 'Преподаватели в расписании',
                'ordering': ['-role', 'teacher__last_name'],
                'unique_together': {('schedule', 'teacher')},
            },
        ),
        migrations.AddField(
            model_name='assessmentschedule',
            name='teachers',
            field=models.ManyToManyField(help_text='Основной преподаватель и со-преподаватели', related_name='assessment_schedules', through='core.AssessmentTeacher', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели'),
        ),
    ]
