# Generated by Django 5.0.6 on 2026-06-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_assessmentschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='basis',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Основание действий'),
        ),
    ]
