# Generated by Django 5.0.6 on 2026-06-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_organization_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='director_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон директора'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='mentor_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон наставника'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='responsible_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон ответственного'),
        ),
    ]
