# Generated by Django 5.0.6 on 2026-07-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_organization_director_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='status',
            field=models.CharField(choices=[('практически_здоров', 'Практически здоров'), ('здоров', 'Здоров'), ('часто_болею', 'Часто болею простудными заболеваниями'), ('хронические_заболевания', 'Имею хронические заболевания'), ('инвалидность', 'Имею инвалидность')], default='практически_здоров', max_length=100, verbose_name='Состояние'),
        ),
    ]
