# Generated by Django 5.0.6 on 2026-07-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_family_status_alter_health_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='status',
            field=models.CharField(choices=[('в_работе', 'В работе'), ('закрыта', 'Закрыта'), ('сдана_в_архив', 'Сдана в архив')], default='в_работе', max_length=50, verbose_name='Статус'),
        ),
    ]
