# Generated by Django 5.0.6 on 2026-07-13 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_statement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False, verbose_name='ID уведомления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка (опционально)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False, verbose_name='ID заявки')),
                ('request_type', models.CharField(choices=[('academic_certificate', 'Академическая справка'), ('study_certificate', 'Справка с места учебы'), ('characteristic', 'Характеристика'), ('other', 'Другое')], max_length=50, verbose_name='Тип заявки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание / Дополнительная информация')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('ready', 'Готово к выдаче')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий куратора/администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Заявка студента',
                'verbose_name_plural': 'Заявки студентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
