# Generated by Django 5.0.6 on 2026-08-04 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification_studentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login_success', 'Успешный вход'), ('login_failed', 'Неудачный вход'), ('logout', 'Выход из системы'), ('password_change', 'Смена пароля'), ('password_reset', 'Сброс пароля администратором'), ('create', 'Создание записи'), ('update', 'Обновление записи'), ('delete', 'Удаление записи'), ('view_sensitive', 'Просмотр чувствительных данных'), ('export', 'Экспорт данных'), ('import', 'Импорт данных'), ('user_block', 'Блокировка пользователя'), ('user_unblock', 'Разблокировка пользователя'), ('role_assign', 'Назначение роли'), ('role_revoke', 'Отзыв роли')], db_index=True, max_length=50, verbose_name='Тип действия')),
                ('object_type', models.CharField(blank=True, help_text='Название модели (User, Student, Passport и т.д.)', max_length=100, verbose_name='Тип объекта')),
                ('object_id', models.CharField(blank=True, help_text='Первичный ключ объекта', max_length=100, verbose_name='ID объекта')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent браузера')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Дополнительная информация в формате JSON', verbose_name='Детали действия')),
                ('content_hash', models.CharField(blank=True, help_text='SHA256 хеш для проверки неизменности записи', max_length=64, verbose_name='Хеш содержимого')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись журнала аудита',
                'verbose_name_plural': 'Записи журнала аудита',
                'db_table': 'core_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action_type'], name='core_auditl_user_id_1a065d_idx'), models.Index(fields=['object_type', 'object_id'], name='core_auditl_object__42e4a9_idx'), models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx')],
            },
        ),
    ]
