# Generated by Django 5.0.6 on 2026-08-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_version',
            field=models.IntegerField(default=1, help_text='Увеличивается при смене пароля для инвалидации старых токенов', verbose_name='Версия пароля'),
        ),
    ]
