# Generated by Django 5.2.17 on 2026-08-08 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_password_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(help_text='Уникальный идентификатор сессии (из JWT jti или сгенерированный)', unique=True, verbose_name='ID сессии')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('expires_at', models.DateTimeField(help_text='Время истечения refresh-токена', verbose_name='Истекает')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия пользователя',
                'verbose_name_plural': 'Сессии пользователей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_userse_user_id_819c57_idx'), models.Index(fields=['session_id'], name='core_userse_session_5d2ebc_idx')],
            },
        ),
    ]
