# Generated by Django 5.2.17 on 2026-08-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_user_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='Обновляется при каждой смене пароля', null=True, verbose_name='Дата смены пароля'),
        ),
    ]
