# Generated by Django 5.2.17 on 2026-08-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_password_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('login_success', 'Успешный вход'), ('login_failed', 'Неудачный вход'), ('logout', 'Выход из системы'), ('password_change', 'Смена пароля'), ('password_reset', 'Сброс пароля администратором'), ('role_switch', 'Переключение роли'), ('create', 'Создание записи'), ('update', 'Обновление записи'), ('delete', 'Удаление записи'), ('view_sensitive', 'Просмотр чувствительных данных'), ('export', 'Экспорт данных'), ('import', 'Импорт данных'), ('user_block', 'Блокировка пользователя'), ('user_unblock', 'Разблокировка пользователя'), ('role_assign', 'Назначение роли'), ('role_revoke', 'Отзыв роли')], db_index=True, max_length=50, verbose_name='Тип действия'),
        ),
    ]
