# Generated by Django 5.2.17 on 2026-08-14 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.IntegerField(help_text='в байтах', verbose_name='Размер файла')),
                ('mode', models.CharField(choices=[('skip_errors', 'Пропуск ошибок'), ('stop_on_error', 'Остановка при ошибке'), ('update_existing', 'Обновление существующих')], max_length=20, verbose_name='Режим импорта')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('processing', 'Обрабатывается'), ('completed', 'Завершен'), ('failed', 'Ошибка'), ('dry_run', 'Сухой прогон')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Всего строк')),
                ('valid_rows', models.IntegerField(default=0, verbose_name='Валидных строк')),
                ('invalid_rows', models.IntegerField(default=0, verbose_name='Невалидных строк')),
                ('created_rows', models.IntegerField(default=0, verbose_name='Создано записей')),
                ('updated_rows', models.IntegerField(default=0, verbose_name='Обновлено записей')),
                ('skipped_rows', models.IntegerField(default=0, verbose_name='Пропущено записей')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Ошибки')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='Предупреждения')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID задачи Celery')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История импорта',
                'verbose_name_plural': 'История импортов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_import_user_id_2a9d69_idx'), models.Index(fields=['status'], name='core_import_status_ca4ad6_idx'), models.Index(fields=['task_id'], name='core_import_task_id_d3bda1_idx')],
            },
        ),
    ]
