# Generated by Django 5.2.17 on 2026-08-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_importhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='inn_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Хэш ИНН'),
        ),
        migrations.AddField(
            model_name='organization',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Непроверена'), ('verified', 'Проверена'), ('blocked', 'Заблокирована'), ('not_found', 'Не найдена в реестре')], default='unverified', max_length=20, verbose_name='Статус верификации'),
        ),
    ]
