# Generated by Django 5.2.17 on 2026-08-22 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_verification_status_to_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementgrade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statementgrade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
    ]
